server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:13306/spring-batch?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&useJDBCCOmpliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: spring-batch
    password: password
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      connection-timeout: 30000
      maximum-pool-size: 200
      minimum-idle: 1
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-test-query: SELECT 1;
      validation-timeout: 28000
      auto-commit: false
  jpa:
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    generate-ddl: false
    open-in-view: false
    properties:
      format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
  batch:
    initialize-schema: never
    job:
      enabled: false
app:
  report:
    output-directory: output
    chunk-size: 1000