version: "3.7"

services:
  mysql-8.0.19:
    image: mysql:8.0.19
    container_name: mysql-8.0.19
    ports:
      - 13306:3306
    ulimits:
      nproc: 514933
      nofile:
        soft: 65535
        hard: 65535
    sysctls:
      net.ipv4.tcp_tw_reuse: 1
      net.ipv4.ip_local_port_range: 1025 65000
    environment:
      - MYSQL_DATABASE=spring-batch
      - MYSQL_USER=spring-batch
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
      - TZ=UTC
    volumes:
      - ./dir/datadir:/var/lib/mysql:rw
      - ./dir/conf.d:/etc/mysql/conf.d:ro
      - ./dir/initdb.d:/docker-entrypoint-initdb.d:ro
#      - ./dir/my.cnf:/root/.my.cnf:ro
#      - ./dir/logs:/var/log/mysql:rw
#      - ./dir/common:/common:ro
#      - ./dir/auto-generate:/auto-generate:rw